Add code for LEAD_02, LEAD_03, LEAD_04
gurug-prog/proj-control pull request #23
Opened 2021-11-27 17:45 UTC by vtarasiuk

2021-11-27 20:10 UTC, gurug-prog requested changes
Good! But there are some common mistakes you have to correct.

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        в системі;
Remove these lines.

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        з усіма завданнями;
Would be better kinda:
1. User clicks the button "Tasks"
2. The system is sending task list to user

...

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        для завдання;
Would be better kinda:
1. The system is sending deadline calendar to user
2. User chooses a deadline for the task

...

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        в системі;
Remove these lines.

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        з списком розробників;
Remove these lines.

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        в системі;
Remove these lines.

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        з усіма завданнями;
Would be better kinda:

1. User clicks the button "Tasks"
2. The system is sending task list to user

...

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        з усіма завданнями;
Would be better kinda:

1. User clicks the button "Tasks"
2. The system is sending task list to user

...

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        завдання;
Remove these lines.

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        введену інформацію;
Remove these lines.

2021-11-27 20:10 UTC, gurug-prog commented on docs/use cases/README.md
> +        результат перевірки;
Replace word "вводить" with "заносить".

2021-11-28 11:35 UTC, gurug-prog approved these changes
LGTM!

2021-11-28 11:47 UTC, SergeyOcheretenko reviewed
LGTM

2021-11-28 11:49 UTC, merged